### ISSUE TITLE
Acceso rápido cuando hay 1 solo ítem

### ISSUE THREAD

**Issue by badgercl** [Ucampus/quicklook#12]
Si un contenedor contiene solo 1 elemento, acceder de inmediato al elemento.
Esto debería ser recursivo hasta encontrar un contenedor con >1 elementos o un item concreto.

**Comment by eriverosr** [comment]
Listo parcialmente, el ingreso automático se realiza siempre que hay una única carpeta en un nivel.

**Comment by eriverosr** [comment]
Al final quedamos en que la mejor idea era solamente ingresar solamente carpetas?
En ese caso, esto estaría resuelto!
