### ISSUE TITLE
agregarle un sourcecolor por javascript al webview para còdigo fuente

### ISSUE THREAD

**Issue by mannungo** [Ucampus/quicklook#19]
ejemplo: https://highlightjs.org/ si no es muy pesado

**Comment by badgercl** [comment]
https://highlightjs.org/
http://prismjs.com/

**Comment by eriverosr** [comment]
En este caso habria que crear un html que hiciera de wrapper al contenido inicial? No estoy muy seguro si es posible introducirlo así no mas, pero quedo de investigar

**Comment by badgercl** [comment]
en Android si :)
https://developer.android.com/intl/es/reference/android/webkit/WebView.html

``` Java
 // OR, you can also load from an HTML string:
 String summary = "<html><body>You scored <b>192</b> points.</body></html>";
 webview.loadData(summary, "text/html", null);
 // ... although note that there are restrictions on what this HTML can do.
 // See the JavaDocs for loadData() and loadDataWithBaseURL() for more info.

```

**Comment by eriverosr** [comment]
Listo! Ahora usa highlight.js y tiene autodetección de código :)
