### ISSUE TITLE
Superposición de controles y FAB en webview

### ISSUE THREAD

**Issue by badgercl** [Ucampus/quicklook#3]
El WebView muestra una botonera de zoom y choca con el Floating Action Button.
![device-2016-01-21-105901](https://cloud.githubusercontent.com/assets/4398862/12482432/33a8c074-c02e-11e5-9463-8bdca9a5de27.png)

**Comment by eriverosr** [comment]
Solucionado!

**Comment by mannungo** [comment]
test

**Comment by mannungo** [comment]
asdf
