### ISSUE TITLE
Agregar botón back en AppBar

### ISSUE THREAD

**Issue by badgercl** [Ucampus/quicklook#4]
Se esta haciendo común que en las apps, incluso en las nativas Android, poner una flecha back (adicionalmente al botón back) en la esquina superior izquierda. Se puede modificando en los XML de layout del Quicklook activity.

![device-2016-01-21-110616](https://cloud.githubusercontent.com/assets/4398862/12482758/2eb6e224-c030-11e5-8816-ca10ae1918e2.png)
![device-2016-01-21-110703](https://cloud.githubusercontent.com/assets/4398862/12482763/318c3990-c030-11e5-8f6b-e431ca1fd2dc.png)

**Comment by eriverosr** [comment]
Agregado
