### ISSUE TITLE
Acceso especial para "archivos" .ql

### ISSUE THREAD

**Issue by badgercl** [Ucampus/quicklook#5]
Dado que los archivos QL no son realmente archivos, sino que información que llega por API, caerían en la categoría de archivo virtual.

Estamos pensando en que debemos actualizar la API de QuickLook para que acepte más datos para permitir extensibilidad pero al mismo tiempo no dar a conocer a otros tipos de archivo sobre estos datos extras.

Actualmente invocamos al QL usando

``` Objective-c
Intent i = new Intent(this, QuicklookActivity.class);
i.putExtra("localurl", urlForAsset);
startActivity(i);
```

Pensamos que para el caso del QL debería enviarse así:

``` Objective-c
Intent i = new Intent(this, QuicklookActivity.class);
i.putExtra("localurl", "nombre del archivo.extension.ql"); //eg Control2015.zip.ql
i.putExtra("json", QL en formato JSON en forma de String); 
startActivity(i);
```

Y dentro del Main Activity, en vez de mandar 4 parámetros a los Item, mandas un quinto que es el Bundle, usualmente el nombre para ese parámetro es _extras_, quedando más o menos así

``` Objective-c
public AItem createItem(String path, String mimetype, String id, long size, Bundle extras) {
        Class c = FileItem.class;
        AItem item = null;
        if (dictionary.containsKey(mimetype)) {
            c = dictionary.get(mimetype);
        }
        try {
            Constructor<?> constructor = c.getConstructor(String.class, String.class, String.class, long.class, Bundle.class);
            item = (AItem)constructor.newInstance(path,mimetype,id,size, extras);
            return item;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return item;
    }
```

en el onCreate puedes obtener el Bundle de extras a través del llamado:

``` Objective-c
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ...
        Bundle extras = getIntent().getExtras();
        ...
   }

```

**Comment by eriverosr** [comment]
¿Eso sería crear un segundo constructor en todos los casos? ¿O modificar el actual? Porque igual en la mayoria de los casos no hay extras que mandar...

EDIT bastaba con editar el createItem para aceptar un quinto elemento y modificar todos los constructores :)

**Comment by eriverosr** [comment]
Completado!
